### ISSUE TITLE
Add the ability for ES to mark the call as spam when a lead tells them that's what they saw on their phone

### ISSUE THREAD

**Issue by epx-nathan** [Epharmix/varys-issues#107]
See Slack thread here for full context: https://caresignal.slack.com/archives/GCD6BA4F6/p1628618913065300

> But actually now that I’m thinking about it, what might make more sense is that on that post-call screen, to have the ability for the ES to check a box if the call was marked as spam. The benefit to that would be that we could add a new column on the Call table like markedAsSpam and then add the number of times a phone call has been reported as spam to the stats in the phone number pool or something.

> We still might want to add “Considered call as spam” to the default rejection reasons dropdown for tracking when the spam designation is the reason a lead rejects enrollment.

**Comment by cs-warshauer** [comment]
In terms of displaying the data on the call screen, it might be helpful to have two fields: # of spam reports all-time and # of spam reports last 30 (or 60) days.

**Comment by epx-nathan** [comment]
This is done and live, so closing this issue!
