### ISSUE TITLE
Find Solution to Excessive Power Dialer Notifications

### ISSUE THREAD

**Issue by cs-britbarrick** [Epharmix/varys-issues#127]
* Feedback from C: 
    * there are an absurd amount of pop-ups that don’t really add helpful or actionable information to the ES’s workflow. Some of the pop-ups could be status changes in-line; some could be redundant and may be removed.
    * But that information could be within Call in Progress area and that the Call Progress block could change the visual state.
* Feedback from Debs:
    * not a fan of all the pop-ups on the upper right, mainly they block the buttons on the upper right side
* Feedback from Dennis:
    *  Maybe we could move the notifications to the top left or bottom right!

**Comment by epx-nathan** [comment]
Closing as this is going live!
