### ISSUE TITLE
Refresh Leads should check isDNC

### ISSUE THREAD

**Issue by cs-warshauer** [Epharmix/varys-issues#138]
Per conversations with Debs, leads are being refreshed after having been marked as DNC.

Proposed solution:

Make it a default where if a lead is going to be refreshed, check to see if they rejected and indicated isDNC = true, and then if that is the case, don’t refresh them. If we need to refresh said patient, they would have to manually have their rejection reason removed and then be re-uploaded. Possible removal from isDNC to ensure the behavior doesn't repeat?

**Comment by epx-nathan** [comment]
This is complete!
