### ISSUE TITLE
Consider keeping deleted VMs for auditing purposes

### ISSUE THREAD

**Issue by epx-nathan** [Epharmix/varys-issues#4]
Originally created by @castavridis 

I think we actually do keep these in the database, just behind a `deletedAt` flag. I can't recall now what the original reasoning for needing it was, but we may be able to get them back. Will investigate further at some point in order to resolve this!

**Comment by cs-olivia** [comment]
Closing this enhancement suggestion as it hasn't been touched/reviewed in a few years.
