### ISSUE TITLE
[Confirm] Update language of successful re-engagement button from "Confirm Enrollment" to "Re-Engaged"

### ISSUE THREAD

**Issue by castavridis** [Epharmix/varys-issues#82]
> Worthwhile to tweak the language for re-engagement campaigns in Varys, which still assumes enrollment language. So if PES successfully re-engages member, they have to select "Confirm Enrollment," which can be confusing. "Re-engaged" or something like that will be less misleading. Also helps the PES team w their call experience.

**Comment by epx-nathan** [comment]
Ah I actually just updated the language used for those buttons today! There is still more to be done in this area, but planning to track this more in #70. Closing this issue!
