### ISSUE TITLE
[Confirm] While exploring Campaigns, let Campaign Search keyword persist via URL or other option

### ISSUE THREAD

**Issue by castavridis** [Epharmix/varys-issues#83]
> For a lot of tasks on the Accounts side, I have to often go back and forth between campaigns of the same account. Searching by acct. names lists all campaigns associated with that account nicely in list form, but as soon as I click into one, I have to run the search all over again. Would be very good utility if we had a working "back" button.

**Comment by epx-nathan** [comment]
This makes sense, and can be done! In the meantime, I also always recommend right clicking and opening the campaign in a new tab so that it's easy to go back. Not an ideal solution, and we can definitely do the above, but just wanted to mention!

**Comment by epx-nathan** [comment]
Will be deploying this tonight, so closing this issue! 🎉
