### ISSUE TITLE
[Confirm] Campaign: Copy / Duplicate Campaign function

### ISSUE THREAD

**Issue by castavridis** [Epharmix/varys-issues#87]
> As campaigns become more nuanced and varied per account, it would be very helpful to have a "duplicate" campaign function instead of creating an entirely new campaign and editing everything over from a similar one.

**Comment by epx-nathan** [comment]
Yes, this would be great to have! I've thought a similar thing before, just haven't had the time to implement.

**Comment by epx-nathan** [comment]
This is done and live!
